# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `2.7.13`
      - image: circleci/python:2.7.13
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/duyquoc.com

    steps:
      - checkout

      # Download and cache dependencies
      - run:
            name: Install dependencies
            command: |
                sudo pip install pelican markdown   
      # Build
      - run:
            name: Build my blog
            command: 
                bash .circleci/build-gh.sh
      # Deploy to GitHub
      - run: 
            name: Deploy content to GitHub
            command:
                bash .circleci/deploy-gh.sh